global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: acserver
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['acserver:5001']
    tls_config:
      insecure_skip_verify: true
#  - job_name: docker_exporter
#    scrape_interval: 30s
#    static_configs:
#      - targets: ['docker_exporter:9417']
  - job_name: docker
    scrape_interval: 20s
    static_configs:
      - targets: ['172.17.0.1:9323']
  - job_name: grafana
    scrape_interval: 20s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: prometheus
    scrape_interval: 20s
    static_configs:
      - targets: ['prometheus:9090']