network:
    version: 2
    ethernets:
        eth0:
            optional: true
            dhcp4: true
    wifis:
        wlan0:
            optional: true
            access-points:
                "ATT3tf4ur4":
                    password: "H3nrB1wan9n3t"
            dhcp4: true
            